import Container from "@/components/container";
import Hero from "@/components/hero";

export const metadata = {
  title: "ブログ | CUBE",
  description: "Generated by create next app",
};

export default function Blog() {
  return (
    <Container>
      <Hero title="Blog" subtitle="Recent Posts" />
    </Container>
  );
}
