import React, { ReactNode } from "react";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { Inter } from "next/font/google";
import "@/app/globals.css";
import { icon } from "@fortawesome/fontawesome-svg-core";

const inter = Inter({ subsets: ["latin"] });

interface LayoutProps {
  children: ReactNode;
}

export const metadata = {
  title: "Home｜CUBE",
  description: "Generated by create next app",
  icons: { icon: "@/public/favicon.ico" },
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
